### ISSUE TITLE
Documentation page is not working

### ISSUE THREAD

**Issue by inagib21** [msoedov/langcorn#26]
Hey, great work on LangCorn. The documentation page seems not working. refer to this page to resolve it.  https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT

**Comment by msoedov** [comment]
Hi @inagib21! Thx for reporting the issue. It seems to be related vercel deployment.

**Comment by PaulLockett** [comment]
Same here. I just started using this and want to pull in some of the features Im seeing on YouTube but I need some clear documentation on this.

**Comment by msoedov** [comment]
Fixed: https://langcorn.vercel.app/docs. There was an issue with `chromadb` installation in ex8.

**Comment by inagib21** [comment]
thank you!
