### ISSUE TITLE
Access to request headers in applications

### ISSUE THREAD

**Issue by pors** [msoedov/langcorn#4]
In many use cases, API keys (like the openAI API key) will be entered by the end user in the client. So instead of getting the API key from an environment variable on the server, it would be cool to get it from a request header.

E.g. the browser POST call has a header `"X-Api-Key": <OPEN_AI_API_KEY>`, which should somehow be accessible by the application.

I don't know enough about FastAPI how to do that. Otherwise, I would have submitted a PR. Just point me in the right direction, and I will provide one.

**Comment by msoedov** [comment]
@pors Thx for the suggestion. Just published a PR to add this feature https://github.com/msoedov/langcorn/pull/12

**Comment by pors** [comment]
Awesome!
